# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Export Header-only Function into R
#'
#' Retrieve a function defined inline from the package's header
#' and surface it into _R_.
#'
#' @param x A `numeric` vector.
#' @param y A single `numeric` value.
#'
#' @return
#'
#' A `numeric vector` that is incremented by a single value.
#'
#' @export
#' @examples
#' x = 1:5
#' y = add_numbers(x, 2)
#' y
add_numbers <- function(x, y) {
    .Call(`_RcppHeaderSharing_add_numbers`, x, y)
}

